name: Web-Client CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: npm
          cache-dependency-path: client/package-lock.json
      
      - name: NPM install
        run: npm ci
        working-directory: client
        
      - name: Build client
        run: npm run build
        working-directory: client
        
      - name: Run tests
        run: npm test
        working-directory: client
      
      - name: Check format
        run: npm run check:format
        working-directory: client
