name: Web-Client CI
# TODO restrict permissions

on:
  push:
    branches: [ main ]
    paths:
      - "client/**"
  pull_request:
    branches: [ main ]
    paths:
      - "client/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build+Test+Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.0.2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 16.x
          cache: npm
          cache-dependency-path: client/package-lock.json
      
      - name: NPM install
        run: npm ci
        working-directory: client
        
      - name: Build client
        run: npm run build:production
        working-directory: client
        
      - name: Run tests
        run: npm test
        working-directory: client

      - name: ESLint
        run: npm run lint
        working-directory: client
      
      - name: Upload client files
        uses: actions/upload-artifact@v3.1.0
        with:
          name: client-files
          path: client/public/*
          retention-days: ${{ (github.ref == 'refs/heads/main') && 90 || 1 }} # 90 days on main branch, 1 for PRs

  compare:
    name: Compare with main
    runs-on: ubuntu-latest
    needs: build
    if: github.ref != 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3.0.2

      - name: Download PR artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: client-files
          path: temp/pr

      - name: Download artifact from main
        uses: benday-inc/download-latest-artifact@v2.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository_owner: KielerGames
          repository_name: ringofsnakes
          workflow_name: "Web-Client CI"
          branch_name: main
          artifact_name: client-files
          download_path: temp
          download_filename: main-branch-client.zip

      - name: Unzip artifact
        run: |
          mkdir temp/main
          unzip temp/main-branch-client.zip -d temp/main

      - name: Compare bundle size
        id: comparison
        uses: NejcZdovc/bundle-size-diff@v1.1.0
        with:
          base_path: temp/main/bundle-stats.json
          pr_path: temp/pr/bundle-stats.json

      - name: Add PR comment
        uses: NejcZdovc/comment-pr@v1.1.1
        with:
          file: pr-client-size-comment.md
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          OLD: ${{steps.comparison.outputs.base_file_string}}
          NEW: ${{steps.comparison.outputs.pr_file_string}}
          DIFF: ${{steps.comparison.outputs.diff_file_string}}
          DIFF_PERCENT: ${{steps.comparison.outputs.percent}}
