name: Web-Client CI

on:
  push:
    branches: [ main ]
    paths:
      - "client/**"
  pull_request:
    branches: [ main ]
    paths:
      - "client/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions: {} # disable all

jobs:
  build:
    name: Build+Test+Lint
    runs-on: ubuntu-latest

    timeout-minutes: 15

    permissions:
      security-events: write

    steps:
      - uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript
          source-root: client/src
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.2.0
        with:
          node-version-file: client/package.json
          cache: npm
          cache-dependency-path: client/package-lock.json
      
      - name: NPM install
        run: npm ci
        working-directory: client
        
      - name: Build client
        env:
          GAME_SERVER: ${{ secrets.GAME_SERVER }}
        run: npm run build:production
        working-directory: client
        
      - name: Run tests
        run: npm test
        working-directory: client

      - name: ESLint
        run: npm run lint
        working-directory: client
      
      - name: Upload client files
        uses: actions/upload-artifact@v4.6.2
        with:
          name: client-files
          path: client/public/*
          retention-days: ${{ (github.ref == 'refs/heads/main') && 32 || 3 }} # 32 days on main branch, 3 for PRs
          if-no-files-found: error

      - name: Cleanup for CodeQL
        run: rm bundle-report.html bundle-stats.json *.LICENSE.txt
        working-directory: client/public

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:javascript"
          upload: ${{ (github.ref == 'refs/heads/main') && 'always' || 'failure-only' }}

  compare:
    name: Compare with main
    runs-on: ubuntu-latest
    needs: build
    if: github.ref != 'refs/heads/main'
    permissions:
      pull-requests: write # required for github/webpack-bundlesize-compare-action

    steps:
      - uses: actions/checkout@v4

      - name: Download PR artifact
        uses: actions/download-artifact@v4.1.9
        with:
          name: client-files
          path: temp/pr

      - name: Download artifact from main
        uses: benday-inc/download-latest-artifact@v2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository_owner: KielerGames
          repository_name: ringofsnakes
          workflow_name: "Web-Client CI"
          branch_name: main
          artifact_name: client-files
          download_path: temp
          download_filename: main-branch-client.zip

      - name: Unzip artifact
        run: |
          mkdir temp/main
          unzip temp/main-branch-client.zip -d temp/main

      - name: Bundle comparison
        uses: github/webpack-bundlesize-compare-action@v2.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          current-stats-json-path: temp/pr/bundle-stats.json
          base-stats-json-path: temp/main/bundle-stats.json
          title: Web client
