# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
    paths:
      - "server/src/**"
      - "server/pom.xml"
  pull_request:
    branches: [ main ]
    paths:
      - "server/src/**"
      - "server/pom.xml"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions: {} # disable all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3.12.0
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: Build & run tests with Maven
        run: mvn --batch-mode test --file pom.xml
        working-directory: server

      - name: Create Uber Jar
        run: mvn --batch-mode package --file pom.xml -Dmaven.test.skip -DskipTests
        working-directory: server

      - name: Upload Uber Jar
        uses: actions/upload-artifact@v3.1.2
        with:
          name: server-uber-jar
          path: server/snake-server-*.jar
          if-no-files-found: error
  
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build
    concurrency: game-server # avoid multiple jobs of this kind to run at the same time
    steps:
      - name: Download jar from previous job
        uses: actions/download-artifact@v3.0.2
        with:
          name: server-uber-jar

      - name: Rename file
        run: mv snake-server-*.jar snake-server.jar

      - name: Initialize SSH
        uses: kielabokkie/ssh-key-and-known-hosts-action@v1.3.5
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}
          ssh-host: ${{ secrets.DEPLOY_SERVER }}
      
      - name: Upload new jar to server
        run: scp snake-server.jar ci@${{ secrets.DEPLOY_SERVER }}:/home/ci

      - name: Restart server
        run: ssh ci@${{ secrets.DEPLOY_SERVER }} "./restart.sh"
