# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
    paths:
      - "server/src/**"
      - "server.pom.xml"
  pull_request:
    branches: [ main ]
    paths:
      - "server/src/**"
      - "server.pom.xml"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.14
    - name: Cache Maven packages
      uses: actions/cache@v2.1.4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build & run tests with Maven
      run: mvn -B test --file pom.xml
      working-directory: server
    - name: Create Uber Jar
      run: mvn -B package --file pom.xml
      working-directory: server
    - name: Upload Uber Jar
      uses: actions/upload-artifact@v2
      with:
        name: server-uber-jar
        path: server/snake-server-*.jar